### ISSUE TITLE
Create a Checklist Issue Template

### ISSUE THREAD

**Issue by DuaneOBrien** [todogroup/work-day-activities#18]
We should have a template for creating future checklists, to make it easier to capture reproducible work.

**Comment by anajsana** [comment]
hey @DuaneOBrien I don't have access to build an issue template directly on this repo ([this doc](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository) explains how to do so on GitHub), but the template draft I had in mind was something like:

## Goal

[Briefly introduce the goal of this issue]

## Description

[Briefly provide a description and/or context of this issue]

## Action Items

[ Set of actions required in order to mark this issue as closed]

- [ ] action item 1
- [ ] action item 2
- [ ] action item 3
- [ ] action item 4

**Comment by DuaneOBrien** [comment]
I'm going to try and land this one today
